spring:
  application:
    name: inventory-processing-service
  kafka:
    consumer:
      group-id: inventory-group

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      auto-offset-reset: earliest
      enable-auto-commit: false

      spring.json.trusted.packages: com.danijelsudimac.order

    listener:
      missing-topics-fatal: false
      ack-mode: manual_immediate
      concurrency: 1

    bootstrap-servers: kafka:29092